name: Update Balance

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  update-balance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies and run script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DATABASE_NAME_1: ${{ secrets.DATABASE_NAME_1 }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          DEFAULT_USER_ADDRESS: ${{ secrets.DEFAULT_USER_ADDRESS }}
          BASE_RPC: ${{ secrets.BASE_RPC }}
          ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
        working-directory: ./detrade-core-usdc/builder
        run: |
          python -m pip install --upgrade pip
          pip install -r ../../requirements.txt
          python pusher.py 