name: Update Balance DeTrade Core USDC & Dev DeTrade Core USDC

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-balance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          BASE_RPC: ${{ secrets.BASE_RPC }}
          ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
        run: python builder/pusher.py 