name: Update Balance DeTrade Core ETH & Dev DeTrade Core ETH

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-balance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          echo "Checking detrade-core-eth directory:"
          ls -la detrade-core-eth || echo "detrade-core-eth not found"
          echo "Checking builder directory:"
          ls -la detrade-core-eth/builder || echo "builder directory not found"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies and run script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          BASE_RPC: ${{ secrets.BASE_RPC }}
          ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
          PYTHONPATH: ${{ github.workspace }}/detrade-core-eth
          DATABASE_NAME: detrade-core-eth
          COLLECTION_NAME: oracle
        working-directory: ${{ github.workspace }}/detrade-core-eth/builder
        run: |
          python -m pip install --upgrade pip
          cd ..
          pip install -r requirements.txt
          cd builder
          python pusher.py 